### ISSUE TITLE
suggestion: change title color

### ISSUE THREAD

**Issue by wzahoor1248** [wajidzahoor/github-cc#1]
I think it looks better if the main titile is a bit more orange

The styling rule could be changed like this
```css
h1 {
  color: #efa82e;
}
```
